import StoreProvider from "api/StoreProvider";
import Header from "components/widgets/header/ui/Header";
import type {Metadata} from "next";
import '../../assets/styles/global.scss';
import '../../assets/styles/null.scss';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
